### PR TITLE
Player Input Movement and Look

### PR DESCRIPTION
**Pull request by George540**
- Added Input System Move & Look properties
- Added Mouse, Keyboard and Gamepad Movements
- Added Unity Events for Student Movement

### CODE REVIEW

**Comment by Laffyyy** [comment]
I think its good but I suggest lowering the clamping of the camera angle by 85 or 80

**Comment by George540** [comment]
> I think its good but I suggest lowering the clamping of the camera angle by 85 or 80 
> 

The camera is irrelevant here tho. Only thing that I worked on was the Player Input, not the camera yet. That will be put in another issue/task. Try not to put as many things into a single branch/task

**Review by Cappic-01 — CHANGES_REQUESTED** [review]
By Unity's naming convention, correct me if I'm wrong, but we should not use the underscore before private members. I'm not against as that's C# convention, but we should follow the guide you sent us for this regard.

**Review by DrakeHunterK7 — COMMENTED** [review]
Looks like everything looks good! Both keyboard mouse and gamepad controls work properly. 

However, as @Cappic-01 noted, you seem to have used the underscore to denote both private and [SerializeField] variables. As per the documentation you sent on our Discord, we are supposed to use underscore for only the [SerializeField] variables. There is no mention of an underscore for private variable names in the documentation.

Of course it's a minor thing but some clarification on this would be much appreciated. Basically do you want us to use underscores for both [SerializeField] variables and private variables, or just one of them (and which one) ?

**Review by Cappic-01 — APPROVED** [review]
Coding conventions agreed on!

**Review by DrakeHunterK7 — APPROVED** [review]
All player movement and input logic working as intended!

**Pull request merged**
